### ISSUE TITLE
hatalı kontrol

### ISSUE THREAD

**Issue by GokhanSevim** [salihsagdilek/tckimlikkontrol#1]
Merhaba,

11111111110 ve 22222222220 kimlik numaralarını invalid dizisinden kaldırmalısın, bu iki kimlik numarası gerçek kişilere aittir.

**Comment by salihsagdilek** [comment]
@GokhanSevim geri bildirimin icin cok tesekkurler, konuyla ilgili haberleri hatirliyorum :) en kisa surede kodu guncellemis olacagim. tesekkurler.

**Comment by GokhanSevim** [comment]
rica ederim, haber olduğunu bilmiyordum, kimlik sorgusunda fark ettim.
